seed: 42

data:
  path: 
  split_ratios: [0.9, 0.05, 0.05] # [train, val, test]
  split_seed: 42
  batch_size: 256
  num_workers: 1

model:
  in_channels: 1
  base_filters: 32
  kernel_size: 3
  stride: 2
  n_block: 16
  hidden_dim: 512
  projection_dim: 512

training:
  logs_dir: 
  checkpoints_dir: 
  optimizer:
    lr: 1e-4
    weight_decay: 1e-5
  loss:
    temperature: 0.07
  early_stopping:
    patience: 10
